export enum ENV_CONSTANT {
  JWT_SECRET = 'JWT_SECRET',
  EXPIRATION_DAY = 'EXPIRATION_DAY',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_DILECT = 'mysql',
}
